# Alpha rarefaction

```{r, include=FALSE}
# at some point this should be moved into bookdown
source("~/Desktop/hpcbio-git/hergenrother-16S-mouse-2022Sept/src/common_code.R", local = knitr::knit_global())
```

```{r}
physeq.filtered <- readRDS('results/physeq.filtered.RDS')
```

Let's check whether we're adequately capturing diversity.  This is a simple alpha rarefaction curve; here we want to see the number of taxa plateau as the counts increase.

```{r, include=FALSE}
p <- suppressMessages(ranacapa::ggrare(physeq.filtered, step = 1000,
            color = "Treatment",
            label = "Label",
            se = FALSE,
            plot = FALSE,
            ))
```

```{r}
p + ggtitle("Alpha Rarefaction")
ggplotly()
```

Promising differences between strains.

```{r}
p <- p + facet_wrap(~Treatment) + ggtitle("Alpha Rarefaction by Treatment")  # theme(legend.position = c(0.8, 0.2))

ggplotly(p)
#ggsave("alpha-rarefaction-byTreatment-separatedbyTreatment.pdf", path = "./results/final-plots", device = pdf, width = 7.5, height = 5, units = "in")
```

Rarefaction looks pretty decent. There may be a few samples that didn't plateau (not all diversity seems to have been captured)