```{r, include=FALSE}
# at some point this should be moved into bookdown
source("~/Desktop/hpcbio-git/caceres-16S-mosquito-2022Sept/src/common_code.R", local = knitr::knit_global())
```

```{r}
physeq.prev <- readRDS("~/Desktop/hpcbio-git/caceres-16S-mosquito-2022Sept/results/phyloseq.prevfiltered.RDS")
```

# Composition plots (filtered data)

Let's look at the taxonomic composition now that the data is filtered. 

```{r}
#Get relative abundance
physeq.prev.prop <- transform_sample_counts(physeq.prev, function(x) x/sum(x) )
sample_data(physeq.prev.prop)$SampleSums <- sample_sums(physeq.prev)

#Pull out top 50 families
#physeq.subset <- tax_glom(physeq.prev.prop, taxrank = "Family")
#tax.ordered <- names(sort(taxa_sums(physeq.subset), TRUE)[1:50])
#physeq.plot <- subset_taxa(physeq.prev.prop, taxa_names(physeq.prev.prop) %in% tax.ordered)

physeq.plot <- physeq.prev.prop
```

Overall compositional summary (stacked bar plots) for all prevalence filtered and tip agglomerated samples.  In this example, all ASVs are included.

```{r, results='asis', fig.keep='all', message = FALSE, warning = FALSE, echo = FALSE}
ranks <- c("Class", "Order", "Family", "Genus", "Species")
plots <- lapply(ranks, function (x) { 

  #Plot relative abundance
  p <- plot_bar(physeq.plot, x="Label", fill = x)
  p1 <- p + theme(legend.key.size = unit(0.25, 'cm'), #change legend key size
        legend.title = element_text(size=6), #change legend title font size
        legend.text = element_text(size=6),
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = 5),
        axis.ticks.x = element_blank()) +
        ylab("Relative Abundance") +
        facet_grid(.~Extr_Env, scales = "free_x", space = "free_x")
       # guides(fill = guide_legend(nrow = 30))
  
#p <- composition_df(physeq, x, minprop = 0.05, keepcols = kc)
#p + facet_wrap(~Location, scales = "free_x", nrow = 1)
  #ggplot(p, aes(x = Label, y = Proportion, fill = print(x, quote=FALSE))) + geom_col() + 
  #  facet_wrap(~Treatment, scales = "free_x") + 
  #  scale_fill_manual(values = dittoSeq::dittoColors(1)) +
  #  theme(axis.text.x = element_text(size = 8, angle = 45, hjust = 1, vjust = 0.5))
 ggplotly(p1)
 # p1
})

names(plots) <- ranks

# Build list of outputs
# See https://stackoverflow.com/questions/9469504/access-and-preserve-list-names-in-lapply-function for example
# not sure if there is an easy way to make a function out of these.
output <- list()
for(rank in ranks){
  # Header for iteration, note Rmd heading ranks and adjust accordingly
  output[[length(output) + 1L]] <- paste0("## ", rank)

  # Plot
  output[[length(output) + 1L]] <- plots[[rank]]
}

# Render the outputs
for(j in 1:length(output)){
  x <- output[[j]]

  if(inherits(x, "character")){
    cat("\n")
    cat(x)
  } else if(inherits(x, "knitr_kable")){
    cat("\n")
    print(x)
  }
  else {
    # print the html piece of the htmlwidgets
    cat("\n")
    cat(htmltools::renderTags(as_widget(x))$html)
  }
}
```

```{r echo=FALSE, messages=FALSE, warning=FALSE}
# Attach the Dependencies since they do not get included with renderTags(...)$html
deps <- lapply(
  Filter(f = function(x){inherits(x,"htmlwidget")}, x = output),
  function(hw){
    htmltools::renderTags(hw)$dependencies
  }
)
htmltools::attachDependencies(x = htmltools::tagList(), value = unlist(deps,recursive=FALSE))
```
